CREATE DATABASE mydb;
USE mydb;
CREATE TABLE apt
(id INT(100) NOT NULL AUTO_INCREMENT PRIMARY KEY,
NAME VARCHAR(255), address VARCHAR(255),
yprice INT(15), dprice INT(15))
ENGINE = INNODB DEFAULT CHARSET = UTF8;
SHOW TABLEs;

